###getAll
GET http://localhost:8080/odata/v4/CatalogService/Books

###get MetaData
GET http://localhost:8080/odata/v4/CatalogService/$metadata

###get a single entity
GET http://localhost:8080/odata/v4/CatalogService/Books(1)

###get a primitive property
GET http://localhost:8080/odata/v4/CatalogService/Books(1)/title

###get the raw value of a primitive property
GET http://localhost:8080/odata/v4/CatalogService/Books(1)/title/$value

###get a primitive property
GET http://localhost:8080/odata/v4/CatalogService/Books(1)/title/$value

###get a primitive property
GET http://localhost:8080/odata/v4/CatalogService/Books(1)/title/$value