---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:./sqlite.db"
    driver-class-name: org.sqlite.JDBC
  web.resources.static-locations: "file:./app"
cds:
  datasource:
    auto-config.enabled: false
  odata-v4.endpoint.path: "/api"
  security.mock.users:
    - name: admin
      password: admin
      roles:
        - admin
    - name: user
      password: user
server:
  port: 4004


