server:
  port: 8189
  servlet:
    context-path: /security
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbs_metadata_defoults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbs:postgressql:localhost:5432/postgres?currentSchema=springsecurity
    username: postgress
    password: admin
