---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:../sqlite.db"
    driver-class-name: org.sqlite.JDBC
cds:
  datasource:
    auto-config.enabled: false
server:
  port: 8081
