### Get all supliers -> 200
GET http://localhost:4004

### Get all supliers -> 401 Unauthorized!!!!!!!!!!
GET http://localhost:4004/owner/Suppliers

### get all addresses -> 401 Unauthorized!!!!!!!!!!
GET http://localhost:4004/customer/Addresses

### get supplier with id=1 -> 401 Unauthorized!!!!!!!!!!
GET http://localhost:4004/owner/Suppliers(1)

### get supplier with id=1 with OData's function $expand > 401 Unauthorized!!!!!!!!!!
GET http://localhost:4004/owner/Suppliers(1)?$expand=Address


### Security
### Unauthorized user
### Get all supliers without role -> 200
GET http://localhost:4004
### Get all supliers without role -> 401
GET http://localhost:4004/odata/v4/OwnerService/Suppliers
### Get all supliers without role -> 401
GET http://localhost:4004/odata/v4/CustomerService/Suppliers

### Аuthorized user
### test public endpoint  -> 200
GET http://user:user@localhost:4004
### Get all supliers as Owner role -> 403 -> "message": "Not authorized to send event 'READ' to 'OwnerService'"
GET http://user:user@localhost:4004/odata/v4/OwnerService/Suppliers
### Get all supliers as Customer -> 200
GET http://user:user@localhost:4004/odata/v4/CustomerService/Suppliers

### Admin
### Get all supliers without role -> 200
GET http://admin:admin@localhost:4004
### Get all supliers with admin -> 200
GET http://localhost:4004/odata/v4/OwnerService/Suppliers
Authorization: Basic YWRtaW46YWRtaW4=
###1 Get all supliers with admin -> 200
GET http://admin:admin@localhost:4004/odata/v4/CustomerService/Suppliers