spring:
  profiles:
    active: dev
server:
  ip: "test-prod"
myapp:
  server-ip: 192.168.34.56
  name: My Config App
  description: This is an example
---
spring:
  config:
    activate:
      on-profile: test
server:
  ip: "test-test"

---
spring:
  config:
    activate:
      on-profile: dev
server:
  ip: "test-dev"